; SMT 2
; Generated for Z3
(set-info :source "Generated by CBMC 4.9")
(set-option :produce-models true)

; find_symbols
(declare-fun |goto_symex::&92;guard#1| () Bool)
; convert
(define-fun B0 () Bool |goto_symex::&92;guard#1|)

; convert
(define-fun B1 () Bool |goto_symex::&92;guard#1|)

; convert
(define-fun B2 () Bool (not |goto_symex::&92;guard#1|))

; convert
(define-fun B3 () Bool (not |goto_symex::&92;guard#1|))

; convert
(define-fun B4 () Bool (not |goto_symex::&92;guard#1|))

; find_symbols
(declare-fun |c::__CPROVER_threads_exited#2| () (Array (_ BitVec 32) Bool))
; convert
(define-fun B5 () Bool (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))))

; convert
(define-fun B6 () Bool (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))))

; convert
(define-fun B7 () Bool (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|))

; convert
(define-fun B8 () Bool (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|))

; convert
(define-fun B9 () Bool (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|))

; convert
(define-fun B10 () Bool (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|))

; convert
(define-fun B11 () Bool (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|))

; convert
(define-fun B12 () Bool (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|))

; convert
(define-fun B13 () Bool (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|))

; find_symbols
(declare-fun |goto_symex::&92;guard#2| () Bool)
; convert
(define-fun B14 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) |goto_symex::&92;guard#2|))

; convert
(define-fun B15 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) |goto_symex::&92;guard#2|))

; convert
(define-fun B16 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|)))

; find_symbols
(declare-fun |goto_symex::&92;guard#3| () Bool)
; convert
(define-fun B17 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|) |goto_symex::&92;guard#3|))

; convert
(define-fun B18 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|) |goto_symex::&92;guard#3|))

; convert
(define-fun B19 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#3|)))

; convert
(define-fun B20 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#3|)))

; find_symbols
(declare-fun |c::__CPROVER_threads_exited#3| () (Array (_ BitVec 32) Bool))
; find_symbols
(declare-fun |c::pthread_join::thread!0@2#1| () (_ BitVec 32))
; convert
(define-fun B21 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)))

; convert
(define-fun B22 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)))

; convert
(define-fun B23 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B24 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B25 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B26 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B27 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B28 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B29 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B30 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B31 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B32 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B33 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B34 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B35 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B36 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B37 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; find_symbols
(declare-fun |goto_symex::&92;guard#4| () Bool)
; convert
(define-fun B38 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|) |goto_symex::&92;guard#4|))

; convert
(define-fun B39 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B40 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B41 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B42 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B43 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B44 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; convert
(define-fun B45 () Bool (and (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|)))

; find_symbols
(declare-fun |goto_symex::&92;guard#5| () Bool)
; convert
(define-fun B46 () Bool |goto_symex::&92;guard#5|)

; convert
(define-fun B47 () Bool |goto_symex::&92;guard#5|)

; convert
(define-fun B48 () Bool |goto_symex::&92;guard#5|)

; convert
(define-fun B49 () Bool |goto_symex::&92;guard#5|)

; find_symbols
(declare-fun |goto_symex::&92;guard#6| () Bool)
; convert
(define-fun B50 () Bool |goto_symex::&92;guard#6|)

; convert
(define-fun B51 () Bool |goto_symex::&92;guard#6|)

; convert
(define-fun B52 () Bool |goto_symex::&92;guard#6|)

; convert
(define-fun B53 () Bool |goto_symex::&92;guard#6|)

; set_to true (equal)
(define-fun |c::a#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |c::b#1| () (_ BitVec 32) (_ bv0 32))

; the following is a substitute for lambda i. x
(declare-fun array_of.0 () (Array (_ BitVec 32) Bool))
; set_to true (equal)
(define-fun |c::__CPROVER_threads_exited#1| () (Array (_ BitVec 32) Bool) array_of.0)

; set_to true (equal)
(define-fun |c::__CPROVER_next_thread_id#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |c::a#2| () (_ BitVec 32) (_ bv8 32))

; set_to true (equal)
(define-fun |c::b#2| () (_ BitVec 32) (_ bv6 32))

; set_to true (equal)
(define-fun |c::__CPROVER_next_thread_id#2| () (_ BitVec 32) (_ bv1 32))

; find_symbols
(declare-fun |c::__CPROVER_next_thread_id#3| () (_ BitVec 32))
; set_to true (equal)
(define-fun |c::__CPROVER_next_thread_id#4| () (_ BitVec 32) (ite (or false false) |c::__CPROVER_next_thread_id#2| |c::__CPROVER_next_thread_id#3|))

; set_to true (equal)
(define-fun |c::__CPROVER_next_thread_id#5| () (_ BitVec 32) (bvadd |c::__CPROVER_next_thread_id#4| (_ bv1 32)))

; set_to true (equal)
(define-fun |c::pthread_create::1::this_thread_id!0@2#2| () (_ BitVec 32) |c::__CPROVER_next_thread_id#5|)

; set_to true (equal)
(define-fun |c::start::1::t2!0@1#2| () (_ BitVec 32) |c::pthread_create::1::this_thread_id!0@2#2|)

; set_to true (equal)
(define-fun |c::__actual_thread_spawn::id!0@2#1| () (_ BitVec 32) |c::pthread_create::1::this_thread_id!0@2#2|)

; set_to true (equal)
(define-fun |c::__actual_thread_spawn::id!2@0#1| () (_ BitVec 32) |c::__actual_thread_spawn::id!0@2#1|)

; find_symbols
(declare-fun |c::__CPROVER_next_thread_id#6| () (_ BitVec 32))
; set_to true
(assert (= |goto_symex::&92;guard#1| (bvult |c::__CPROVER_next_thread_id#6| (_ bv1 32))))

; set_to true
(assert (= |c::pthread_join::thread!0@2#1| |c::start::1::t2!0@1#2|))

; find_symbols
(declare-fun |c::__CPROVER_next_thread_id#7| () (_ BitVec 32))
; set_to true
(assert (= |goto_symex::&92;guard#2| (not (bvuge |c::__CPROVER_next_thread_id#7| |c::pthread_join::thread!0@2#1|))))

; set_to true
(assert (= |goto_symex::&92;guard#3| (= |c::pthread_join::thread!0@2#1| (_ bv0 32))))

; find_symbols
(declare-fun |c::a#3| () (_ BitVec 32))
; set_to true (equal)
(define-fun |c::start#return_value!0#1| () (_ BitVec 32) |c::a#3|)

; set_to true (equal)
(define-fun |c::main::$tmp::return_value_start$1!0@1#2| () (_ BitVec 32) |c::start#return_value!0#1|)

; set_to true (equal)
(define-fun |c::check_gcd::gcd!0@1#1| () (_ BitVec 32) |c::main::$tmp::return_value_start$1!0@1#2|)

; set_to true (equal)
(define-fun |c::__VERIFIER_assert::cond!0@1#1| () (_ BitVec 32) (ite (and (not (= |c::check_gcd::gcd!0@1#1| (_ bv8 32))) (not (= |c::check_gcd::gcd!0@1#1| (_ bv6 32)))) (_ bv1 32) (_ bv0 32)))

; set_to true
(assert (= |goto_symex::&92;guard#4| (not (not (= |c::__VERIFIER_assert::cond!0@1#1| (_ bv0 32))))))

; find_symbols
(declare-fun |c::b#3| () (_ BitVec 32))
; find_symbols
(declare-fun |c::a#4| () (_ BitVec 32))
; set_to true
(assert (= |goto_symex::&92;guard#5| (not (bvuge |c::b#3| |c::a#4|))))

; find_symbols
(declare-fun |c::a#5| () (_ BitVec 32))
; find_symbols
(declare-fun |c::b#4| () (_ BitVec 32))
; set_to true (equal)
(define-fun |c::a#6| () (_ BitVec 32) (bvadd |c::a#5| (bvneg |c::b#4|)))

; find_symbols
(declare-fun |c::__CPROVER_threads_exited#4| () (Array (_ BitVec 32) Bool))
; set_to true (equal)
(define-fun |c::__CPROVER_threads_exited#5| () (Array (_ BitVec 32) Bool) (store |c::__CPROVER_threads_exited#4| (_ bv1 32) true))

; find_symbols
(declare-fun |c::a#7| () (_ BitVec 32))
; find_symbols
(declare-fun |c::b#5| () (_ BitVec 32))
; set_to true
(assert (= |goto_symex::&92;guard#6| (not (bvuge |c::a#7| |c::b#5|))))

; find_symbols
(declare-fun |c::b#6| () (_ BitVec 32))
; find_symbols
(declare-fun |c::a#8| () (_ BitVec 32))
; set_to true (equal)
(define-fun |c::b#7| () (_ BitVec 32) (bvadd |c::b#6| (bvneg |c::a#8|)))

; find_symbols
(declare-fun |c::__CPROVER_threads_exited#6| () (Array (_ BitVec 32) Bool))
; set_to true (equal)
(define-fun |c::__CPROVER_threads_exited#7| () (Array (_ BitVec 32) Bool) (store |c::__CPROVER_threads_exited#6| |c::__actual_thread_spawn::id!2@0#1| true))

; set_to true
(assert (or (and (not |goto_symex::&92;guard#1|) (select |c::__CPROVER_threads_exited#2| (_ bv1 32))) |goto_symex::&92;guard#1|))

; set_to true
(assert (or (and (not |goto_symex::&92;guard#2|) (or (and (not |goto_symex::&92;guard#3|) (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#3|)) |goto_symex::&92;guard#2|))

; set_to true
(assert |goto_symex::&92;guard#4|)

; find_symbols
(declare-fun |memory_model::choice_rf0| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf0|) (= |c::__CPROVER_next_thread_id#3| |c::__CPROVER_next_thread_id#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf1| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf1|) (= |c::__CPROVER_next_thread_id#3| |c::__CPROVER_next_thread_id#2|)))

; set_to true
(assert (or |memory_model::choice_rf0| |memory_model::choice_rf1|))

; find_symbols
(declare-fun |memory_model::choice_rf2| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf2|) (= |c::__CPROVER_next_thread_id#6| |c::__CPROVER_next_thread_id#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf3| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf3|) (= |c::__CPROVER_next_thread_id#6| |c::__CPROVER_next_thread_id#2|)))

; find_symbols
(declare-fun |memory_model::choice_rf4| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf4|) (= |c::__CPROVER_next_thread_id#6| |c::__CPROVER_next_thread_id#5|)))

; set_to true
(assert (or |memory_model::choice_rf2| |memory_model::choice_rf3| |memory_model::choice_rf4|))

; find_symbols
(declare-fun |memory_model::choice_rf5| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf5|) (= |c::__CPROVER_threads_exited#2| |c::__CPROVER_threads_exited#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf6| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf6|) (= |c::__CPROVER_threads_exited#2| |c::__CPROVER_threads_exited#5|)))

; find_symbols
(declare-fun |memory_model::choice_rf7| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf7|) (= |c::__CPROVER_threads_exited#2| |c::__CPROVER_threads_exited#7|)))

; set_to true
(assert (or |goto_symex::&92;guard#1| |memory_model::choice_rf5| |memory_model::choice_rf6| |memory_model::choice_rf7|))

; find_symbols
(declare-fun |memory_model::choice_rf8| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf8|) (= |c::__CPROVER_next_thread_id#7| |c::__CPROVER_next_thread_id#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf9| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf9|) (= |c::__CPROVER_next_thread_id#7| |c::__CPROVER_next_thread_id#2|)))

; find_symbols
(declare-fun |memory_model::choice_rf10| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf10|) (= |c::__CPROVER_next_thread_id#7| |c::__CPROVER_next_thread_id#5|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (not (select |c::__CPROVER_threads_exited#2| (_ bv1 32)))) (not |goto_symex::&92;guard#1|)) |memory_model::choice_rf8| |memory_model::choice_rf9| |memory_model::choice_rf10|))

; find_symbols
(declare-fun |memory_model::choice_rf11| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf11|) (= |c::__CPROVER_threads_exited#3| |c::__CPROVER_threads_exited#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf12| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf12|) (= |c::__CPROVER_threads_exited#3| |c::__CPROVER_threads_exited#5|)))

; find_symbols
(declare-fun |memory_model::choice_rf13| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf13|) (= |c::__CPROVER_threads_exited#3| |c::__CPROVER_threads_exited#7|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (not (select |c::__CPROVER_threads_exited#2| (_ bv1 32)))) (not |goto_symex::&92;guard#1|)) |goto_symex::&92;guard#2| |goto_symex::&92;guard#3| |memory_model::choice_rf11| |memory_model::choice_rf12| |memory_model::choice_rf13|))

; find_symbols
(declare-fun |memory_model::choice_rf14| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf14|) (and (= |c::a#3| |c::a#6|) |goto_symex::&92;guard#5|)))

; find_symbols
(declare-fun |memory_model::choice_rf15| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf15|) (= |c::a#3| |c::a#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf16| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf16|) (= |c::a#3| |c::a#2|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (not (select |c::__CPROVER_threads_exited#2| (_ bv1 32)))) (not |goto_symex::&92;guard#1|)) (and (or |goto_symex::&92;guard#2| (and (or |goto_symex::&92;guard#3| (not (select |c::__CPROVER_threads_exited#3| |c::pthread_join::thread!0@2#1|))) (not |goto_symex::&92;guard#3|))) (not |goto_symex::&92;guard#2|)) |memory_model::choice_rf14| |memory_model::choice_rf15| |memory_model::choice_rf16|))

; find_symbols
(declare-fun |memory_model::choice_rf17| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf17|) (= |c::a#4| |c::a#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf18| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf18|) (= |c::a#4| |c::a#2|)))

; set_to true
(assert (or |memory_model::choice_rf17| |memory_model::choice_rf18|))

; find_symbols
(declare-fun |memory_model::choice_rf19| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf19|) (= |c::b#3| |c::b#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf20| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf20|) (= |c::b#3| |c::b#2|)))

; find_symbols
(declare-fun |memory_model::choice_rf21| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf21|) (and (= |c::b#3| |c::b#7|) |goto_symex::&92;guard#6|)))

; set_to true
(assert (or |memory_model::choice_rf19| |memory_model::choice_rf20| |memory_model::choice_rf21|))

; find_symbols
(declare-fun |memory_model::choice_rf22| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf22|) (= |c::a#5| |c::a#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf23| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf23|) (= |c::a#5| |c::a#2|)))

; set_to true
(assert (or (not |goto_symex::&92;guard#5|) |memory_model::choice_rf22| |memory_model::choice_rf23|))

; find_symbols
(declare-fun |memory_model::choice_rf24| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf24|) (= |c::b#4| |c::b#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf25| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf25|) (= |c::b#4| |c::b#2|)))

; find_symbols
(declare-fun |memory_model::choice_rf26| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf26|) (and (= |c::b#4| |c::b#7|) |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (not |goto_symex::&92;guard#5|) |memory_model::choice_rf24| |memory_model::choice_rf25| |memory_model::choice_rf26|))

; find_symbols
(declare-fun |memory_model::choice_rf27| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf27|) (= |c::__CPROVER_threads_exited#4| |c::__CPROVER_threads_exited#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf28| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf28|) (= |c::__CPROVER_threads_exited#4| |c::__CPROVER_threads_exited#7|)))

; set_to true
(assert (or |memory_model::choice_rf27| |memory_model::choice_rf28|))

; find_symbols
(declare-fun |memory_model::choice_rf29| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf29|) (= |c::b#5| |c::b#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf30| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf30|) (= |c::b#5| |c::b#2|)))

; set_to true
(assert (or |memory_model::choice_rf29| |memory_model::choice_rf30|))

; find_symbols
(declare-fun |memory_model::choice_rf31| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf31|) (= |c::a#7| |c::a#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf32| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf32|) (= |c::a#7| |c::a#2|)))

; find_symbols
(declare-fun |memory_model::choice_rf33| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf33|) (and (= |c::a#7| |c::a#6|) |goto_symex::&92;guard#5|)))

; set_to true
(assert (or |memory_model::choice_rf31| |memory_model::choice_rf32| |memory_model::choice_rf33|))

; find_symbols
(declare-fun |memory_model::choice_rf34| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf34|) (= |c::b#6| |c::b#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf35| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf35|) (= |c::b#6| |c::b#2|)))

; set_to true
(assert (or (not |goto_symex::&92;guard#6|) |memory_model::choice_rf34| |memory_model::choice_rf35|))

; find_symbols
(declare-fun |memory_model::choice_rf36| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf36|) (= |c::a#8| |c::a#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf37| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf37|) (= |c::a#8| |c::a#2|)))

; find_symbols
(declare-fun |memory_model::choice_rf38| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf38|) (and (= |c::a#8| |c::a#6|) |goto_symex::&92;guard#5|)))

; set_to true
(assert (or (not |goto_symex::&92;guard#6|) |memory_model::choice_rf36| |memory_model::choice_rf37| |memory_model::choice_rf38|))

; find_symbols
(declare-fun |memory_model::choice_rf39| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf39|) (= |c::__CPROVER_threads_exited#6| |c::__CPROVER_threads_exited#1|)))

; find_symbols
(declare-fun |memory_model::choice_rf40| () Bool)
; set_to true
(assert (or (not |memory_model::choice_rf40|) (= |c::__CPROVER_threads_exited#6| |c::__CPROVER_threads_exited#5|)))

; set_to true
(assert (or |memory_model::choice_rf39| |memory_model::choice_rf40|))

; set_to true
(assert (or (not |memory_model::choice_rf27|) (not |memory_model::choice_rf39|)))

(check-sat)

(get-value (|B0|))
(get-value (|B1|))
(get-value (|B10|))
(get-value (|B11|))
(get-value (|B12|))
(get-value (|B13|))
(get-value (|B14|))
(get-value (|B15|))
(get-value (|B16|))
(get-value (|B17|))
(get-value (|B18|))
(get-value (|B19|))
(get-value (|B2|))
(get-value (|B20|))
(get-value (|B21|))
(get-value (|B22|))
(get-value (|B23|))
(get-value (|B24|))
(get-value (|B25|))
(get-value (|B26|))
(get-value (|B27|))
(get-value (|B28|))
(get-value (|B29|))
(get-value (|B3|))
(get-value (|B30|))
(get-value (|B31|))
(get-value (|B32|))
(get-value (|B33|))
(get-value (|B34|))
(get-value (|B35|))
(get-value (|B36|))
(get-value (|B37|))
(get-value (|B38|))
(get-value (|B39|))
(get-value (|B4|))
(get-value (|B40|))
(get-value (|B41|))
(get-value (|B42|))
(get-value (|B43|))
(get-value (|B44|))
(get-value (|B45|))
(get-value (|B46|))
(get-value (|B47|))
(get-value (|B48|))
(get-value (|B49|))
(get-value (|B5|))
(get-value (|B50|))
(get-value (|B51|))
(get-value (|B52|))
(get-value (|B53|))
(get-value (|B6|))
(get-value (|B7|))
(get-value (|B8|))
(get-value (|B9|))
(get-value (|c::__CPROVER_next_thread_id#1|))
(get-value (|c::__CPROVER_next_thread_id#2|))
(get-value (|c::__CPROVER_next_thread_id#3|))
(get-value (|c::__CPROVER_next_thread_id#4|))
(get-value (|c::__CPROVER_next_thread_id#5|))
(get-value (|c::__CPROVER_next_thread_id#6|))
(get-value (|c::__CPROVER_next_thread_id#7|))
(get-value (|c::__CPROVER_threads_exited#1|))
(get-value (|c::__CPROVER_threads_exited#2|))
(get-value (|c::__CPROVER_threads_exited#3|))
(get-value (|c::__CPROVER_threads_exited#4|))
(get-value (|c::__CPROVER_threads_exited#5|))
(get-value (|c::__CPROVER_threads_exited#6|))
(get-value (|c::__CPROVER_threads_exited#7|))
(get-value (|c::__VERIFIER_assert::cond!0@1#1|))
(get-value (|c::__actual_thread_spawn::id!0@2#1|))
(get-value (|c::__actual_thread_spawn::id!2@0#1|))
(get-value (|c::a#1|))
(get-value (|c::a#2|))
(get-value (|c::a#3|))
(get-value (|c::a#4|))
(get-value (|c::a#5|))
(get-value (|c::a#6|))
(get-value (|c::a#7|))
(get-value (|c::a#8|))
(get-value (|c::b#1|))
(get-value (|c::b#2|))
(get-value (|c::b#3|))
(get-value (|c::b#4|))
(get-value (|c::b#5|))
(get-value (|c::b#6|))
(get-value (|c::b#7|))
(get-value (|c::check_gcd::gcd!0@1#1|))
(get-value (|c::main::$tmp::return_value_start$1!0@1#2|))
(get-value (|c::pthread_create::1::this_thread_id!0@2#2|))
(get-value (|c::pthread_join::thread!0@2#1|))
(get-value (|c::start#return_value!0#1|))
(get-value (|c::start::1::t2!0@1#2|))
(get-value (|goto_symex::&92;guard#1|))
(get-value (|goto_symex::&92;guard#2|))
(get-value (|goto_symex::&92;guard#3|))
(get-value (|goto_symex::&92;guard#4|))
(get-value (|goto_symex::&92;guard#5|))
(get-value (|goto_symex::&92;guard#6|))
(get-value (|memory_model::choice_rf0|))
(get-value (|memory_model::choice_rf1|))
(get-value (|memory_model::choice_rf10|))
(get-value (|memory_model::choice_rf11|))
(get-value (|memory_model::choice_rf12|))
(get-value (|memory_model::choice_rf13|))
(get-value (|memory_model::choice_rf14|))
(get-value (|memory_model::choice_rf15|))
(get-value (|memory_model::choice_rf16|))
(get-value (|memory_model::choice_rf17|))
(get-value (|memory_model::choice_rf18|))
(get-value (|memory_model::choice_rf19|))
(get-value (|memory_model::choice_rf2|))
(get-value (|memory_model::choice_rf20|))
(get-value (|memory_model::choice_rf21|))
(get-value (|memory_model::choice_rf22|))
(get-value (|memory_model::choice_rf23|))
(get-value (|memory_model::choice_rf24|))
(get-value (|memory_model::choice_rf25|))
(get-value (|memory_model::choice_rf26|))
(get-value (|memory_model::choice_rf27|))
(get-value (|memory_model::choice_rf28|))
(get-value (|memory_model::choice_rf29|))
(get-value (|memory_model::choice_rf3|))
(get-value (|memory_model::choice_rf30|))
(get-value (|memory_model::choice_rf31|))
(get-value (|memory_model::choice_rf32|))
(get-value (|memory_model::choice_rf33|))
(get-value (|memory_model::choice_rf34|))
(get-value (|memory_model::choice_rf35|))
(get-value (|memory_model::choice_rf36|))
(get-value (|memory_model::choice_rf37|))
(get-value (|memory_model::choice_rf38|))
(get-value (|memory_model::choice_rf39|))
(get-value (|memory_model::choice_rf4|))
(get-value (|memory_model::choice_rf40|))
(get-value (|memory_model::choice_rf5|))
(get-value (|memory_model::choice_rf6|))
(get-value (|memory_model::choice_rf7|))
(get-value (|memory_model::choice_rf8|))
(get-value (|memory_model::choice_rf9|))

(exit)
; end of SMT2 file
